import {
  acceptRewardRequestTerms,
  acceptSavingsGoalCounter,
  approveSavingsGoalCompletion,
  cancelSavingsGoal,
  claimApprovedRewardProposal,
  claimJob,
  clearChildSessionCode,
  contributeToFamilyFund,
  contributeSavingsAccountToFamilyFund,
  contributeSavingsAccountToSavingsGoal,
  contributeToSavingsGoal,
  createChildProfile,
  createFeedbackEntry,
  createCustomRewardRequest,
  createGoal,
  createHousehold,
  createJob,
  createReward,
  deleteChildProfile,
  declineRewardRequestTerms,
  declineSavingsGoalCounter,
  dismissAllRewardNotifications,
  dismissRewardNotification,
  fulfillRewardRequest,
  markJobAsMissed,
  moveSavingsAccountToWallet,
  moveWalletCreditsToSavingsAccount,
  requestJobCheck,
  requestReward,
  resolveRewardRequestAsPool,
  reviewJobCheckRequest,
  reviewRewardRequest,
  reviewSavingsGoalRequest,
  setChildAllowSessionCode,
  setChildSessionCode,
  setChildSessionSecurity,
  setFamilyAnnouncement,
  updateChildProfile,
  updateJob,
  updateReward,
} from '../services/familyEconomyService'
import { familyMutation } from './familyEconomyApiUtils'

const DASHBOARD_TAGS = ['FamilyDashboard', 'FamilyHome', 'ParentCommandCenter']
const HOUSEHOLD_TAGS = ['FamilyHome', 'HouseholdOnboarding', 'ParentCommandCenter']
const JOB_CHECK_TAGS = ['FamilyDashboard', 'FamilyHome', 'FamilyJobChecks', 'FamilyConsequences', 'HouseholdOnboarding', 'ParentCommandCenter']
const STORE_TAGS = ['FamilyDashboard', 'FamilyHome', 'FamilyStore', 'ParentCommandCenter']
const FEEDBACK_TAGS = ['FamilyFeedback', 'ParentCommandCenter']

export function buildFamilyMutationEndpoints(builder) {
  return {
    claimJob: familyMutation(
      builder,
      ({ jobId, context }) => claimJob(jobId, context),
      'Could not claim job.',
      DASHBOARD_TAGS,
    ),
    requestJobCheck: familyMutation(
      builder,
      ({ job, context }) => requestJobCheck(job, context),
      'Could not request a job check.',
      ['FamilyDashboard', 'FamilyHome', 'FamilyJobChecks', 'ParentCommandCenter'],
    ),
    reviewJobCheckRequest: familyMutation(
      builder,
      ({ requestId, decision, context }) => reviewJobCheckRequest(requestId, decision, context),
      'Could not review job check request.',
      JOB_CHECK_TAGS,
    ),
    markJobAsMissed: familyMutation(
      builder,
      ({ jobId, context }) => markJobAsMissed(jobId, context),
      'Could not mark this job as missed.',
      JOB_CHECK_TAGS,
    ),
    createHousehold: familyMutation(
      builder,
      ({ household, context }) => createHousehold(household, context),
      'Could not save household details.',
      HOUSEHOLD_TAGS,
    ),
    createChildProfile: familyMutation(
      builder,
      ({ childProfile, context }) => createChildProfile(childProfile, context),
      'Could not add child profile.',
      HOUSEHOLD_TAGS,
    ),
    updateChildProfile: familyMutation(
      builder,
      ({ childId, childProfile, context }) => updateChildProfile(childId, childProfile, context),
      'Could not update child profile.',
      HOUSEHOLD_TAGS,
    ),
    deleteChildProfile: familyMutation(
      builder,
      ({ childId, context }) => deleteChildProfile(childId, context),
      'Could not remove child profile.',
      HOUSEHOLD_TAGS,
    ),
    setChildSessionSecurity: familyMutation(
      builder,
      ({ enabled, context }) => setChildSessionSecurity(enabled, context),
      'Could not update child session security setting.',
      HOUSEHOLD_TAGS,
    ),
    setChildAllowSessionCode: familyMutation(
      builder,
      ({ childId, allowed, context }) => setChildAllowSessionCode(childId, allowed, context),
      'Could not update child PIN permission.',
      HOUSEHOLD_TAGS,
    ),
    clearChildSessionCode: familyMutation(
      builder,
      ({ childId, context }) => clearChildSessionCode(childId, context),
      'Could not clear child PIN.',
      HOUSEHOLD_TAGS,
    ),
    setFamilyAnnouncement: familyMutation(
      builder,
      ({ announcement, context }) => setFamilyAnnouncement(announcement, context),
      'Could not save family announcement.',
      HOUSEHOLD_TAGS,
    ),
    createJob: familyMutation(
      builder,
      ({ jobPayload, context }) => createJob(jobPayload, context),
      'Could not add starter job.',
      ['FamilyDashboard', 'FamilyHome', 'HouseholdOnboarding', 'ParentCommandCenter'],
    ),
    updateJob: familyMutation(
      builder,
      ({ jobId, jobPayload, context }) => updateJob(jobId, jobPayload, context),
      'Could not update job.',
      ['FamilyDashboard', 'FamilyHome', 'HouseholdOnboarding', 'ParentCommandCenter'],
    ),
    createReward: familyMutation(
      builder,
      ({ rewardPayload, context }) => createReward(rewardPayload, context),
      'Could not add starter reward.',
      ['FamilyStore', 'FamilyHome', 'HouseholdOnboarding', 'ParentCommandCenter'],
    ),
    updateReward: familyMutation(
      builder,
      ({ rewardId, rewardPayload, context }) => updateReward(rewardId, rewardPayload, context),
      'Could not update reward.',
      ['FamilyStore', 'FamilyHome', 'HouseholdOnboarding', 'ParentCommandCenter'],
    ),
    requestReward: familyMutation(
      builder,
      ({ reward, context }) => requestReward(reward, context),
      'Could not submit reward request.',
      STORE_TAGS,
    ),
    reviewRewardRequest: familyMutation(
      builder,
      ({ requestId, decision, context, options }) => reviewRewardRequest(requestId, decision, context, options),
      'Could not review reward request.',
      STORE_TAGS,
    ),
    resolveRewardRequestAsPool: familyMutation(
      builder,
      ({ requestId, rewardPayload, context, options }) => resolveRewardRequestAsPool(requestId, rewardPayload, context, options),
      'Could not add this request to the family reward pool.',
      STORE_TAGS,
    ),
    fulfillRewardRequest: familyMutation(
      builder,
      ({ requestId, context }) => fulfillRewardRequest(requestId, context),
      'Could not mark reward as fulfilled.',
      STORE_TAGS,
    ),
    dismissRewardNotification: familyMutation(
      builder,
      ({ requestId, context }) => dismissRewardNotification(requestId, context),
      'Could not dismiss reward notification.',
      STORE_TAGS,
    ),
    dismissAllRewardNotifications: familyMutation(
      builder,
      ({ context }) => dismissAllRewardNotifications(context),
      'Could not dismiss all reward notifications.',
      STORE_TAGS,
    ),
    createCustomRewardRequest: familyMutation(
      builder,
      ({ requestPayload, context }) => createCustomRewardRequest(requestPayload, context),
      'Could not request this reward yet.',
      STORE_TAGS,
    ),
    acceptRewardRequestTerms: familyMutation(
      builder,
      ({ requestId, context }) => acceptRewardRequestTerms(requestId, context),
      'Could not accept these reward terms.',
      STORE_TAGS,
    ),
    declineRewardRequestTerms: familyMutation(
      builder,
      ({ requestId, context }) => declineRewardRequestTerms(requestId, context),
      'Could not decline these reward terms.',
      STORE_TAGS,
    ),
    claimApprovedRewardProposal: familyMutation(
      builder,
      ({ requestId, context }) => claimApprovedRewardProposal(requestId, context),
      'Could not claim this approved reward yet.',
      STORE_TAGS,
    ),
    createGoal: familyMutation(
      builder,
      ({ goalPayload, context }) => createGoal(goalPayload, context),
      'Could not request savings goal.',
      DASHBOARD_TAGS,
    ),
    approveSavingsGoalCompletion: familyMutation(
      builder,
      ({ goalId, context }) => approveSavingsGoalCompletion(goalId, context),
      'Could not approve this savings goal yet.',
      DASHBOARD_TAGS,
    ),
    reviewSavingsGoalRequest: familyMutation(
      builder,
      ({ goalId, decision, context, options }) => reviewSavingsGoalRequest(goalId, decision, context, options),
      'Could not review this goal request.',
      DASHBOARD_TAGS,
    ),
    contributeToSavingsGoal: familyMutation(
      builder,
      ({ goalId, amount, context }) => contributeToSavingsGoal(goalId, amount, context),
      'Could not move credits into savings.',
      DASHBOARD_TAGS,
    ),
    contributeToFamilyFund: familyMutation(
      builder,
      ({ amount, context }) => contributeToFamilyFund(amount, context),
      'Could not move credits into the family fund.',
      DASHBOARD_TAGS,
    ),
    moveWalletCreditsToSavingsAccount: familyMutation(
      builder,
      ({ amount, context }) => moveWalletCreditsToSavingsAccount(amount, context),
      'Could not move credits into the savings account.',
      DASHBOARD_TAGS,
    ),
    moveSavingsAccountToWallet: familyMutation(
      builder,
      ({ amount, context }) => moveSavingsAccountToWallet(amount, context),
      'Could not move savings back to wallet.',
      DASHBOARD_TAGS,
    ),
    contributeSavingsAccountToSavingsGoal: familyMutation(
      builder,
      ({ goalId, amount, context }) => contributeSavingsAccountToSavingsGoal(goalId, amount, context),
      'Could not contribute savings to this goal.',
      DASHBOARD_TAGS,
    ),
    contributeSavingsAccountToFamilyFund: familyMutation(
      builder,
      ({ amount, context }) => contributeSavingsAccountToFamilyFund(amount, context),
      'Could not contribute savings to the family fund.',
      DASHBOARD_TAGS,
    ),
    cancelSavingsGoal: familyMutation(
      builder,
      ({ goalId, context }) => cancelSavingsGoal(goalId, context),
      'Could not cancel savings goal.',
      DASHBOARD_TAGS,
    ),
    acceptSavingsGoalCounter: familyMutation(
      builder,
      ({ goalId, context }) => acceptSavingsGoalCounter(goalId, context),
      'Could not accept this counter offer.',
      DASHBOARD_TAGS,
    ),
    declineSavingsGoalCounter: familyMutation(
      builder,
      ({ goalId, context }) => declineSavingsGoalCounter(goalId, context),
      'Could not decline this counter offer.',
      DASHBOARD_TAGS,
    ),
    setChildSessionCode: familyMutation(
      builder,
      ({ childId, sessionCode, context }) => setChildSessionCode(childId, sessionCode, context),
      'Could not set child session code.',
      HOUSEHOLD_TAGS,
    ),
    createFeedbackEntry: familyMutation(
      builder,
      ({ feedbackPayload, context }) => createFeedbackEntry(feedbackPayload, context),
      'Could not submit feedback.',
      FEEDBACK_TAGS,
    ),
  }
}
